services:
  db:
    image: mysql:8.0.27
    container_name: "mysql"
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ../kubedata/mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password!
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - 3306
      - 33060
    networks:
      - wp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "phpmyadmin"
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db:3306
      PMA_USER: admin
      PMA_PASSWORD: password!
    ports:
      - "8383:80"
    networks:
      - wp

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    container_name: "wp"
    volumes:
      - ../kubedata/wp:/var/www/html/wp-content
      - ../kubedata/www:/var/www/html
      - ../kubedata/certs:/etc/ssl/certs:ro
      - ./default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_WEBSITE_URL="https://localhost"
      - WORDPRESS_WEBSITE_URL_WITHOUT_HTTP=localhost
    networks:
      - wp

networks:
  wp:






